### ISSUE TITLE
Bug: Go library build error

### ISSUE THREAD

**Issue by BruceMacD** [unum-cloud/usearch#177]
### Describe the bug

Running the example I get this error:
```
# github.com/unum-cloud/usearch/golang
../go/pkg/mod/github.com/unum-cloud/usearch/golang@v0.0.0-20230720201502-ff268f175932/lib.go:10:10: fatal error: '../c/usearch.h' file not found
#include "../c/usearch.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
```

Looking through the compiled package I see that this path doesn't exist. 

Reference: https://github.com/unum-cloud/usearch/tree/main/golang

### Steps to reproduce

- create a Go project
- `go get https://github.com/unum-cloud/usearch`
- try to run the example `go run .`

### Expected behavior

library runs without issue

### USearch version

v0.0.0-20230720201502-ff268f175932

### Operating System

Mac OS Ventura

### Hardware architecture

x86

### Which interface are you using?

Other bindings

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hey, @BruceMacD! I have refactored GoLang bindings and wrote new tests, so the issue should be gone, but there is still no pre-built package. As we are done with the 1.0 release, I will now focus on that 🤗

**Comment by ashvardanian** [comment]
After every "Semantic Release", we will attach a pre-compiled binary for every central platform to the "release assets". There are several GitHub CI extensions for that. We can use the default ones. The whole pipeline should be pretty straightforward - spin up the VM or container, compile the C library, put it into the GoLang directory, compile GoLang bindings, bundle them with the static library, and upload them to assets. The resulting CI Action may look like this, ofc adjusting for different library names on different OSes, and adding the bundling code. @gurgenyegoryan, please take this over.

```yml
  publish_golang:
    name: Publish Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'  
    - run: git submodule update --init --recursive
    - run: cd golang && make -C ../c build && mv ../c/libusearch.a libusearch.a && go test -v
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./golang"
        binary_name: "lib"
        extra_files: LICENSE README.md
```

The only concern I have is that default tools may not allow compiling for WebAssembly, but let's fix the common case first.
